baseURL = 'blog.gagelara.com'
languageCode = 'en-us'
title = "Gage Lara's Blog"
theme = 'github-style'

[params]
  author = "Gage Lara"
  description = "NixOS, DevOps, and Cloud enthusiast. I also make music and TTRPG stuff. "
  github = "metamageia"
  linkedin = "gage-lara"
  email = "metamageia@gmail.com"
  url = "blog.gagelara.com"
  keywords = "blog"
  rss = true
  lastmod = true
  favicon = "/blog.gagelara/images/github-mark.png"
  avatar = "/blog.gagelara/images/avatar.png"
  headerIcon = "/blog.gagelara/images/github-mark-white.png"
  location = "El Dorado, Ks"
  enableGitalk = false
  enableSearch = true
